version: '3.8'

services:
  ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
