services:
  ai-backend:
    build:
      context: .
      dockerfile: Dockerfile.q-base
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - Q_LOG_LEVEL=info
      - PORT=3001
    volumes:
      - uploads:/home/quser/workspace/uploads
      - memories:/home/quser/workspace/个人记忆
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
  memories:
