version: '3.8'

services:
  ai-assistant:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./个人记忆:/home/quser/app/个人记忆
      - ./uploads:/home/quser/app/uploads
    restart: unless-stopped
