services:
  - type: web
    name: ai-assistant-backend
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: ai-assistant-backend
          property: port
